
using QDM version '5.0'

valueset "Rehabilitation Assessment": 'Rehabilitation Assessment'
valueset "Rehabilitation Therapy": 'Rehabilitation Therapy'
valueset "Patient Refusal": 'Patient Refusal'
valueset "Medical Reason": 'Medical Reason'
valueset "Non-Elective Inpatient Encounter": 'Non-Elective Inpatient Encounter'
valueset "Discharged to Rehabilitation Facility": 'Discharged to Rehabilitation Facility'

parameter "Measurement Period" Interval<DateTime>
