
/*
How can we have two events around a single procedure?
For example, how can we reference two instances of an assessment
 one before a procedure and one after a procedure?
 This is just a general question. Since, we can't iterate through
 the lists of Assessments or list of procedures.
*/

using QDM version '5.4'

valueset "Some Procedure Value Set": 'TBD'
valueset "Some Assessment Value Set": 'TBD'
