
using QDM version '5.0.2'

valueset "Cardiopulmonary arrest Grouping Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.748'
valueset "Electrocardiogram (ECG) Grouping Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.735'
valueset "Emergency Department Visit SNOMEDCT Value Set": 'urn:oid:2.16.840.1.113883.3.117.1.7.1.292'
valueset "Encounter Inpatient SNOMEDCT Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.307'
valueset "Fibrinolytic Therapy RXNORM Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.736'
valueset "Aortic balloon pump insertion SNOMEDCT Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.1151'
valueset "Endotracheal Intubation Grouping Value Set": 'urn:oid:2.16.840.1.113762.1.4.1045.69'
valueset "PCI Grouping Value Set": 'urn:oid:2.16.840.1.113762.1.4.1045.67'
valueset "Ventricular Assist Device placement Grouping Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.3015'
valueset "Ambulatory surgical center SNOMEDCT Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.687'
valueset "Transfer From Emergency Department (ED) Locations SNOMEDCT Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.3006'
valueset "Transfer From Inpatient SNOMEDCT Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.3013'
valueset "Transfer From Outpatient SNOMEDCT Value Set": 'urn:oid:2.16.840.1.113883.3.67.1.101.950'
valueset "STEMI Exclusions Grouping Value Set": 'urn:oid:2.16.840.1.113762.1.4.1045.36'
valueset "Acute Myocardial Infarction (AMI) Grouping Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.3011'
valueset "Acute or Evolving MI Grouping Value Set": 'urn:oid:2.16.840.1.113883.3.666.5.3022'

valueset "Ethnicity": 'urn:oid:2.16.840.1.114222.4.11.837'
valueset "Payer": 'urn:oid:2.16.840.1.114222.4.11.3591'
valueset "Race": 'urn:oid:2.16.840.1.114222.4.11.836'
valueset "ONC Administrative Sex": 'urn:oid:2.16.840.1.113762.1.4.1'

parameter "Measurement Period" Interval<DateTime>
