
using QDM version '5.0.2'

// NOTE: Simplified measure definition for illustration purposes only

valueset "Prostate Cancer": 'urn:oid:2.16.840.1.113883.3.526.3.319' 
valueset "Patient Reason Refused": 'urn:oid:2.16.840.1.113883.3.600.1.1503' 
valueset "Androgen deprivation therapy for Urology Care": 'urn:oid:2.16.840.1.113762.1.4.1151.48' 
valueset "Male": 'urn:oid:2.16.840.1.113883.3.560.100.1' 
valueset "Injection Leuprolide Acetate": 'urn:oid:2.16.840.1.113762.1.4.1151.16' 
valueset "Office Visit": 'urn:oid:2.16.840.1.113883.3.464.1003.101.12.1001' 

parameter "Measurement Period" Interval<DateTime>
