
// https://oncprojectracking.healthit.gov/support/browse/CQLIT-65

using QDM version '5.3'

valueset "Encounter Inpatient": 'urn:oid:2.16.840.1.113883.3.666.5.307'
valueset "Single Live Birth": 'urn:oid:2.16.840.1.113883.3.117.1.7.1.25'
valueset "Single Live Born Newborn Born in Hospital": 'urn:oid:2.16.840.1.113883.3.117.1.7.1.26'
valueset "Gestational Diabetes": '1.2.3'

parameter "Measurement Period" Interval<DateTime>
