/*
This library illustrates patterns for accessing related FHIR resources through
references. Although timing is often used to establish relationships between
events in quality measures and decision support logic, if the model supports
explicit relationships (_references_ in FHIR), then those can be used as part
of where clauses and such that criteria, as illustrated by the examples in
this library.
*/
library FHIRReferences